export default {
  login: 'amgillenwater',
  id: 63607748,
  node_id: 'MDQ6VXNlcjYzNjA3NzQ4',
  avatar_url: 'https://avatars2.githubusercontent.com/u/63607748?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/amgillenwater',
  html_url: 'https://github.com/amgillenwater',
  followers_url: 'https://api.github.com/users/amgillenwater/followers',
  following_url: 'https://api.github.com/users/amgillenwater/following{/other_user}',
  gists_url: 'https://api.github.com/users/amgillenwater/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/amgillenwater/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/amgillenwater/subscriptions',
  organizations_url: 'https://api.github.com/users/amgillenwater/orgs',
  repos_url: 'https://api.github.com/users/amgillenwater/repos',
  events_url: 'https://api.github.com/users/amgillenwater/events{/privacy}',
  received_events_url: 'https://api.github.com/users/amgillenwater/received_events',
  type: 'User',
  site_admin: false,
  name: 'Ashley Gillenwater',
  company: 'Momentum Learning',
  blog: '',
  location: 'Durham, NC',
  email: null,
  hireable: null,
  bio: 'Living in Durham, NC and coding with my three keyboard warmers (🐈🐈🐈)',
  twitter_username: 'amgillenwater',
  public_repos: 9,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2020-04-13T17:47:26Z',
  updated_at: '2020-08-27T11:20:01Z'
}
